"""Put the chain-carousel test rig into Onshape (issue #128).

    python onshape_build.py create      # new public company document + import + views + version
    python onshape_build.py views       # re-render Onshape's shaded views of the recorded document

One composite import of ../step/chain_carousel_rig.step (flattenAssemblies
false) gives an Assembly tab whose tree is the build sequence (one
sub-assembly per assembly step) plus one Part Studio per unique part, with
every instance already placed. That is the cheapest route the lab has
measured (PR #176 notes): a dozen-odd calls instead of one per instance.
Ids land in onshape_document.json; every call is in api_calls.jsonl.
"""
from __future__ import annotations

import argparse
import base64
import json
import time
from pathlib import Path

from client import HERE, Onshape

ROOT = HERE.parent
STEP = ROOT / "step" / "chain_carousel_rig.step"
DOC_JSON = HERE / "onshape_document.json"
RENDERS = ROOT / "renders" / "onshape"
COMPANY_NAME = "Vertical Cloud Lab"
DOC_NAME = "Multi-doser chain carousel - test rig v0 (#128)"
DESCRIPTION = ("ANSI #35 chain loop (96 links, two 19T sprockets, C = 366.71 mm) with 12 carriages on A-1 "
               "attachment links, NEMA 34 drive, HDPE deck on a 2020 frame, station hold-downs and hall "
               "sensors; module 1 carries Sam's Oct 8 mounting plate and the lab auger. Generated by "
               "vertical-cloud-lab/powder-doser cad/chain-carousel (CadQuery -> STEP -> REST API). "
               "Git is the source of truth; edits here come back as reviewed imports.")


def company_id(c: Onshape) -> str:
    for it in c.get("/companies")["items"]:
        if it["name"] == COMPANY_NAME:
            return it["id"]
    raise RuntimeError(f"the API key is not in {COMPANY_NAME}")


def import_assembly(c: Onshape, did: str, wid: str) -> dict:
    data = STEP.read_bytes()
    fname = STEP.name
    form = {"encodedFilename": fname, "fileContentLength": str(len(data)), "translate": "true",
            "flattenAssemblies": "false", "yAxisIsUp": "false", "allowFaultyParts": "true"}
    res = c.post(f"/blobelements/d/{did}/w/{wid}", files={"file": (fname, data, "application/step")}, data=form)
    tid = res.get("translationId") or res["id"]
    time.sleep(45)
    for _ in range(12):
        st = c.get(f"/translations/{tid}")
        if st["requestState"] == "DONE":
            return st
        if st["requestState"] == "FAILED":
            raise RuntimeError(f"translation failed: {st.get('failureReason')}")
        time.sleep(25)
    raise RuntimeError("translation still running; re-poll /translations/" + tid)


def shaded(c: Onshape, rec: dict, name: str, view: str, w: int = 1600, h: int = 1000) -> Path:
    did, wid, aid = rec["documentId"], rec["workspaceId"], rec["assemblyElementId"]
    r = c.get(f"/assemblies/d/{did}/w/{wid}/e/{aid}/shadedviews",
              params={"viewMatrix": view, "outputHeight": h, "outputWidth": w, "pixelSize": 0,
                      "edges": "show", "useAntiAliasing": "true"})
    RENDERS.mkdir(parents=True, exist_ok=True)
    out = RENDERS / f"onshape_{name}.png"
    out.write_bytes(base64.b64decode(r["images"][0]))
    return out


# Onshape view matrices are the 3x4 camera rotation, row-major (12 numbers):
# this one looks from front-right-above, like renders/rig_iso.png.
FRONT_ISO = "0.8,0.6,0,0,-0.36,0.48,0.8,0,0.48,-0.64,0.6,0"


def create() -> dict:
    c = Onshape(budget=30, run="create-document")
    cid = company_id(c)
    doc = c.post("/documents", json={"name": DOC_NAME, "ownerId": cid, "ownerType": 1, "isPublic": True,
                                     "description": DESCRIPTION})
    did, wid = doc["id"], doc["defaultWorkspace"]["id"]
    rec = {"documentId": did, "workspaceId": wid, "owner": COMPANY_NAME, "public": True,
           "url": f"https://cad.onshape.com/documents/{did}/w/{wid}"}
    DOC_JSON.write_text(json.dumps(rec, indent=1))
    st = import_assembly(c, did, wid)
    rec["translationId"] = st["id"]
    rec["importedElementIds"] = st.get("resultElementIds", [])
    els = c.get(f"/documents/d/{did}/w/{wid}/elements")
    rec["elements"] = [{"id": e["id"], "name": e["name"], "type": e.get("elementType")} for e in els]
    asm = [e for e in els if e.get("elementType") == "ASSEMBLY"]
    top = next((e for e in asm if e["name"].startswith("Chain carousel")), asm[0] if asm else None)
    rec["assemblyElementId"] = top["id"] if top else None
    rec["assemblyUrl"] = f"{rec['url']}/e/{rec['assemblyElementId']}"
    DOC_JSON.write_text(json.dumps(rec, indent=1))
    if rec["assemblyElementId"]:
        for name, view in (("iso", "isometric"), ("front_iso", FRONT_ISO), ("top", "top")):
            try:
                print("->", shaded(c, rec, name, view))
            except RuntimeError as e:
                print("view", name, "failed:", str(e)[:200])
    v = c.post(f"/documents/d/{did}/versions", json={"documentId": did, "name": "v1 chain test rig",
                                                      "description": "Import from cad/chain-carousel (#128): 303 instances, "
                                                                     "45 parts, no interferences over 0.5 mm^3"})
    rec["version"] = {"id": v["id"], "name": v["name"]}
    rec["api_calls"] = c.calls
    DOC_JSON.write_text(json.dumps(rec, indent=1))
    print(json.dumps(rec, indent=1)[:2000])
    return rec


def supersede(old_json: Path, new: dict) -> None:
    """Rename an earlier document so nobody edits it by mistake (the API key
    has no delete scope, so it can't be removed)."""
    old = json.loads(old_json.read_text())
    c = Onshape(budget=2, run="supersede")
    c.post(f"/documents/{old['documentId']}", json={
        "name": f"{DOC_NAME} - SUPERSEDED, see {new['documentId'][:8]}",
        "description": f"Superseded by {new['url']} (same rig, frame and fastener fixes). Kept because the API key "
                       "cannot delete documents."})
    old["superseded_by"] = new["url"]
    old_json.write_text(json.dumps(old, indent=1))


def views() -> None:
    rec = json.loads(DOC_JSON.read_text())
    c = Onshape(budget=4, run="views")
    for name, view in (("iso", "isometric"), ("front_iso", FRONT_ISO)):
        print("->", shaded(c, rec, name, view))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["create", "views"])
    ap.add_argument("--supersede", type=Path, help="earlier onshape_document*.json to mark superseded")
    a = ap.parse_args()
    if a.cmd == "create":
        rec = create()
        if a.supersede:
            supersede(a.supersede, rec)
    else:
        views()
