#!/usr/bin/env python3
"""Write the SI test-protocol records table from the committed run and record CSVs.

Folded in from PR #150 (``paper/protocols/make_protocol_table.py`` on branch
``claude/test-protocol-table``). Table 3 of the main text already specifies
protocols A--H in tube angles and auger units, so this table carries what that
one does not:

* the settings exactly as the raw records store them (tilt as a servo setting,
  speeds and targets as sent to the firmware), so a reader can match a raw CSV
  row to a protocol; and
* how many runs asked for each protocol, how many produced records, how many
  records there are, and how many of those come from runs that passed screening.

Counts are computed here, so they cannot drift from the data:

* runs requesting a protocol: ``runs_all.csv`` (``blocks`` column, both rounds);
* protocols A--E records: ``../candidates/data/trials.csv`` (round 1; the
  firmware labels each record with a ``block`` letter, a wire-format name that
  is left unchanged);
* protocols G and H records: ``doses_all.csv`` (both rounds), where a record is
  one dose attempt and ``dose_valid`` marks the 99 doses the paper scores.

Usage:  python3 make_protocol_records_table.py   (writes protocol_records_table.tex)
"""

from __future__ import annotations

import pathlib

import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
TRIALS = HERE.parent / "candidates" / "data" / "trials.csv"

# Settings as the raw records and the battery firmware store them
# (powder_battery.py, BATTERY_VERSION = 2; main_three_phase.py for G and H).
# Tilt is a servo setting; the 2:1 tilt gear makes 0/45/90 into tube angles of
# 0, 22.5 and 45 degrees. Rotations and speeds are already auger units.
PROTOCOLS = [
    ("A", "Balance baseline", r"tilt 45; 8 reads; no actuator"),
    ("B", "Static hold", r"tilt 0, 45, 90; 15~s hold each"),
    ("C", "Rotation", r"tilt 0, 45, 90; 6 $\times$ 360$^\circ$ at 30~rpm"),
    ("D", "Speed sweep", r"tilt 45; 15, 45, 90~rpm; 3~rev commanded; poll 250~ms"),
    ("E", "Tap", r"tilt 0, 45; 8 $\times$ (360$^\circ$ re-feed + one 60~ms tap)"),
    ("F", "Vibration", r"tilt 0, 45; as E with 3 ERM bursts"),
    ("G", "Closed-loop, 1~g", r"3 doses; target 1000~mg"),
    ("H", "Closed-loop, small", r"3 doses each; targets 50 and 200~mg"),
]


def main() -> None:
    runs = pd.read_csv(HERE / "runs_all.csv")
    runs = runs[runs["blocks"].notna()]
    valid_runs = set(runs.loc[runs["qc_valid"].astype(bool), "run_id"])

    trials = pd.read_csv(TRIALS)
    doses = pd.read_csv(HERE / "doses_all.csv")

    rows = []
    for key, name, settings in PROTOCOLS:
        asked = runs[runs["blocks"].str.contains(key)]
        n_asked = {r: int((asked["round"] == r).sum()) for r in (1, 2)}
        if key in "ABCDEF":
            rec = trials[trials["block"] == key]
            n_rec = len(rec)
            n_runs_rec = rec["run_id"].nunique()
            n_used = int(rec["run_id"].isin(valid_runs).sum())
        else:
            # Two demonstration doses on 1 Sep 2026 (issue #148) have no run
            # record in runs_all.csv; count only runs in the run inventory.
            rec = doses[(doses["block"] == key) & doses["run_id"].isin(runs["run_id"])]
            n_rec = len(rec)
            n_runs_rec = rec["run_id"].nunique()
            n_used = int(rec["dose_valid"].astype(bool).sum())
        rows.append((key, name, settings, n_asked[1], n_asked[2], n_runs_rec, n_rec, n_used))

    # Guard the numbers the main text quotes.
    by_key = {r[0]: r for r in rows}
    assert by_key["F"][6] == 0, "protocol F should have no records"
    assert by_key["G"][7] + by_key["H"][7] == 99, "expected 99 valid doses"

    head = (r"\multicolumn{2}{@{}l}{Protocol} & Settings in the raw records & "
            r"\multicolumn{2}{c}{Runs asking} & Runs with & Records & From screened \\")
    sub = r" & & & Round 1 & Round 2 & records & & runs \\"
    lines = [
        "% Generated by paper/figures/data/make_protocol_records_table.py -- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\caption{Test protocols as they appear in the raw records, and how many records "
        r"each produced. Table~3 of the main text gives the same protocols in tube angles. "
        r"Here tilt is the servo setting the records store (0, 45, or 90), which the 2:1 "
        r"tilt gear turns into tube angles of 0$^\circ$, 22.5$^\circ$, and 45$^\circ$. "
        r"The firmware and the CSV files identify the protocols by the same letters, in a "
        r"field named \texttt{block}. A record is one trial for protocols A--E (for "
        r"example, one auger revolution in C, or one re-feed or one tap in E) and one "
        r"dose attempt for G and H. \emph{From screened runs} counts the records from "
        r"runs that passed screening; for G and H it counts the doses scored in the main "
        r"text, after the exclusions listed in Table~\ref{tbl:doseaccount}. "
        r"Protocol D's timing loop turned the auger 15--54\% further than the three "
        r"revolutions commanded (Experimental). Every run requesting protocol F logged a "
        r"skip because the haptic driver did not respond. Two demonstration doses on "
        r"1 September 2026 that have no run record are left out. Counts are computed from "
        r"\texttt{runs\_all.csv}, \texttt{trials.csv}, and \texttt{doses\_all.csv} in "
        r"\texttt{paper/figures/}.}",
        r"\label{tbl:protocolrecords}",
        r"\begin{tabular}{@{}l >{\raggedright\arraybackslash}p{2.2cm} "
        r">{\raggedright\arraybackslash}p{4.4cm} cc ccc@{}}",
        r"\toprule",
        head,
        r"\cmidrule(lr){4-5}",
        sub,
        r"\midrule",
    ]
    for key, name, settings, a1, a2, nr, n, used in rows:
        lines.append(f"{key} & {name} & {settings} & {a1} & {a2} & {nr} & {n} & {used} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (HERE / "protocol_records_table.tex").write_text("\n".join(lines))
    for r in rows:
        print(r)
    print("wrote protocol_records_table.tex")


if __name__ == "__main__":
    main()
