#!/usr/bin/env python3
"""Write the SI run-inventory table (Table S3) from runs_all.csv.

One row per recorded run in both test rounds: when it started, which powder
and test protocols it covered, where the rig stood, how many closed-loop doses
it attempted, and the outcome of quality screening. The screening codes in
runs_all.csv are translated to plain words here; the CSV keeps the codes.

Usage:  python3 make_run_inventory.py   (writes run_inventory_table.tex)
"""

from __future__ import annotations

import pathlib

import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent

LOCATION = {
    "lab_pre_hood": "open bench",
    "shared_fume_hood": "fume hood 1",
    "new_fume_hood": "fume hood 2",
}

SCREENING = {
    "ok": "passed",
    "conveying-slowly": "passed (slow delivery)",
    "no-conveyance-auger-suspect": "excluded: nothing delivered, auger suspected",
    "no-conveyance-outlet-unverified": "excluded: nothing delivered, outlet not checked",
    "no-tilt-servo-fault": "excluded: tilt servo failed",
    "environment-stress-test": "excluded: deliberate bench stress test",
    "doser-scale-unreadable": "excluded: balance could not be read",
    "outlet-misaligned": "excluded: outlet misaligned",
    "arching-no-feed": "excluded: powder caked in the tube",
    "aborted-before-battery": "aborted before testing",
    "dose-gate stand-down (no battery run)": "postponed: failed the stability check",
    "demo": "demonstration only",
    "unreviewed": "demonstration only",
}

POWDER_TEX = {
    "Si (-110/+200 mesh)": r"Si ($-$110/+200 mesh)",
    "Si (-325 mesh)": r"Si ($-$325 mesh)",
    "NaCl (control)": "NaCl",
}


def main() -> None:
    runs = pd.read_csv(HERE / "runs_all.csv")
    runs["start"] = pd.to_datetime(runs["started_utc"], utc=True, format="ISO8601")
    runs = runs.sort_values("start")

    unknown = set(runs["qc_verdict"]) - set(SCREENING)
    if unknown:
        raise SystemExit(f"untranslated screening codes: {sorted(unknown)}")

    head = (r"Start (UTC) & Round & Powder & Protocols & Location & Doses & Screening \\")
    lines = [
        "% Generated by paper/figures/data/make_run_inventory.py -- do not edit by hand.",
        r"\begin{longtable}{lclllr>{\raggedright\arraybackslash}p{4.4cm}}",
        r"\caption{Every recorded run in both test rounds, in date order. \emph{Protocols} "
        r"lists the test protocols the run requested (Table~3 of the main text; "
        r"protocol F never produced data); "
        r"\emph{Doses} is the number of closed-loop doses attempted. Locations: an "
        r"open laboratory bench (to 6 August 2026), a shared fume hood (11 August to "
        r"3 September), and a second fume hood (from 3 September). Runs that failed screening are "
        r"listed here and in \texttt{paper/figures/data/runs\_all.csv} with the reason; "
        r"the Experimental section describes how runs were chosen for each figure.}"
        r"\label{tbl:runs}\\",
        r"\toprule", head, r"\midrule\endfirsthead",
        r"\toprule", head, r"\midrule\endhead",
    ]
    for _, r in runs.iterrows():
        powder = r["display"] if isinstance(r["display"], str) else "--"
        powder = POWDER_TEX.get(powder, powder)
        protocols = r["blocks"] if isinstance(r["blocks"], str) else "--"
        lines.append(
            f"{r['start']:%Y-%m-%d %H:%M} & {int(r['round'])} & {powder} & "
            f"{protocols} & {LOCATION[r['location']]} & {int(r['n_doses'])} & "
            f"{SCREENING[r['qc_verdict']]} \\\\"
        )
    lines += [r"\bottomrule", r"\end{longtable}", ""]
    (HERE / "run_inventory_table.tex").write_text("\n".join(lines))
    print(f"wrote run_inventory_table.tex ({len(runs)} runs)")


if __name__ == "__main__":
    main()
