#!/usr/bin/env python3
"""Refresh the powder-doser bench broadcast listing used by the run log.

The bench camera streams continuously to
https://youtube.com/@byu-vcl-hardware-streams in rolling 8 h broadcasts, so
every battery run is already on video.  Finding *which* video means mapping a
run's wall-clock start onto a broadcast, and each broadcast announces its own
window in its title::

    powder doser stream picam-d1pr, 2026-08-20 UTC 19:00

This script reads the channel's stream listing and writes those windows to
``docs/battery-runs/stream-broadcasts.json``.  ``scripts/build_run_log.py``
then joins runs to broadcasts without any per-run manual work.

YouTube bot-blocks the CI runner's datacenter IP, so the listing is fetched
over the Pi's residential connection by default (``--via-pi``).  Transfers are
rate-capped per CLAUDE.md, and the Pi's hostname and credentials come from the
environment and are never printed.

Usage::

    python scripts/refresh_stream_broadcasts.py            # fetch via the Pi
    python scripts/refresh_stream_broadcasts.py --local    # fetch directly

Note what this listing is *not*: ``nominal_start_utc`` is the broadcast-accepted
time from the title, not the video's t=0.  On the one broadcast calibrated
against the burned-in overlay clock, t=0 was 66 s later.  Links derived from it
are accurate to about a minute -- enough to find a run or a block, not enough to
land on a specific auger revolution.  For that, calibrate the broadcast into
``stream-registry.json`` (see ``battery_stream_links.py --calibrate``); the run
log prefers a calibrated anchor whenever one exists.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path

CHANNEL = "https://youtube.com/@byu-vcl-hardware-streams"
CAMERA = "picam-d1pr"
RATE_LIMIT = "500K"
DEFAULT_OUT = Path("docs/battery-runs/stream-broadcasts.json")

TITLE_RE = re.compile(
    r"^(?P<what>.+?) stream (?P<cam>[\w-]+), "
    r"(?P<date>\d{4}-\d{2}-\d{2}) UTC (?P<h>\d{2}):(?P<m>\d{2})$"
)

HEADER_COMMENT = [
    "Powder-doser bench broadcasts on https://youtube.com/@byu-vcl-hardware-streams.",
    "",
    "Generated by scripts/refresh_stream_broadcasts.py, which reads the channel's",
    "stream listing through the Pi's residential connection (YouTube bot-blocks the",
    "CI runner's datacenter IP) and parses each title of the form",
    "  'powder doser stream picam-d1pr, YYYY-MM-DD UTC HH:MM'.",
    "",
    "nominal_start_utc comes from that title, so it is the broadcast-accepted time,",
    "NOT the video's t=0. On the one broadcast that has been calibrated against the",
    "burned-in overlay clock (2026-08-04 19:00), content t=0 was 19:01:06 UTC, i.e.",
    "66 s after the nominal start. So a ?t= offset computed from nominal_start_utc",
    "lands within roughly a minute -- good enough to find a run or a block, not good",
    "enough to land on a specific auger revolution.",
    "",
    "For frame-accurate links, calibrate the broadcast and add it to",
    "stream-registry.json; scripts/build_run_log.py prefers a calibrated anchor and",
    "falls back to the nominal start, marking the difference in the log.",
    "",
    "Broadcasts roll over every 8 h at 03:00 / 11:00 / 19:00 UTC.",
]

REMOTE_PARSE = r"""
import json, sys
d = json.load(sys.stdin)
print(json.dumps([
    {"video_id": e.get("id"), "title": e.get("title"),
     "live_status": e.get("live_status")}
    for e in d.get("entries", [])
]))
"""


def _pi_target() -> str:
    user = os.environ.get("RPI_POWDER_DOSER_USERNAME")
    host = os.environ.get("RPI_POWDER_DOSER_HOSTNAME")
    if not user or not host:
        sys.exit(
            "set RPI_POWDER_DOSER_USERNAME and RPI_POWDER_DOSER_HOSTNAME "
            "(injected by the workflow; never print their values)"
        )
    return f"{user}@{host}"


def fetch_via_pi(venv: str) -> list[dict]:
    remote = (
        f"{venv}/bin/yt-dlp --flat-playlist --limit-rate {RATE_LIMIT} -J "
        f"{shlex.quote(CHANNEL + '/streams')} 2>/dev/null | "
        f"{venv}/bin/python -c {shlex.quote(REMOTE_PARSE)}"
    )
    proc = subprocess.run(
        ["ssh", "-o", "StrictHostKeyChecking=no", _pi_target(), remote],
        capture_output=True, text=True,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        # Never echo the Pi's hostname or the command, per CLAUDE.md.
        sys.exit("could not fetch the channel listing through the Pi")
    return json.loads(proc.stdout)


def fetch_local() -> list[dict]:
    proc = subprocess.run(
        ["yt-dlp", "--flat-playlist", "--limit-rate", RATE_LIMIT, "-J",
         CHANNEL + "/streams"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        sys.exit(
            "could not fetch the channel listing directly -- YouTube usually "
            "bot-blocks datacenter IPs; try without --local"
        )
    d = json.loads(proc.stdout)
    return [
        {"video_id": e.get("id"), "title": e.get("title"),
         "live_status": e.get("live_status")}
        for e in d.get("entries", [])
    ]


def parse_entries(entries: list[dict], camera: str) -> list[dict]:
    out = []
    for e in entries:
        title = (e.get("title") or "").strip()
        m = TITLE_RE.match(title)
        if not m or m.group("cam") != camera:
            continue
        out.append({
            "video_id": e["video_id"],
            "title": title,
            "camera": camera,
            "nominal_start_utc":
                f"{m.group('date')}T{m.group('h')}:{m.group('m')}:00+00:00",
            "live_status": e.get("live_status"),
        })
    out.sort(key=lambda r: r["nominal_start_utc"])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--camera", default=CAMERA)
    ap.add_argument("--local", action="store_true",
                    help="fetch directly instead of through the Pi")
    ap.add_argument("--pi-venv", default="~/powder-doser-venv")
    args = ap.parse_args()

    entries = fetch_local() if args.local else fetch_via_pi(args.pi_venv)
    broadcasts = parse_entries(entries, args.camera)
    if not broadcasts:
        sys.exit(f"no broadcasts matched camera {args.camera}")

    doc = {
        "_comment": HEADER_COMMENT,
        "channel": CHANNEL,
        "camera": args.camera,
        "broadcasts": broadcasts,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"[broadcasts] wrote {len(broadcasts)} to {args.out}")
    print(f"[broadcasts] {broadcasts[0]['nominal_start_utc']} "
          f"-> {broadcasts[-1]['nominal_start_utc']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
